name: nasa_galllery
description: A NASA Gallery App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data.json
    - assets/fonts:Poppins/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font:Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font:Poppins/Poppins-ThinItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font:Poppins/Poppins-ExtraLightItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font:Poppins/Poppins-LightItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font:Poppins/Poppins-RegularItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font:Poppins/Poppins-MediumItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font:Poppins/Poppins-SemiBoldItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font:Poppins/Poppins-BoldItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font:Poppins/Poppins-ExtraBoldItalic.ttf
          style: italic

        - asset: assets/font:Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/font:Poppins/Poppins-BlackItalic.ttf
          style: italic